<?php

namespace ContainerGIT1GFH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportProductsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ImportProductsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ImportProductsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:import-products', ['app:import-products'], 'Обработка файла', false, #[\Closure(name: 'App\\Command\\ImportProductsCommand')] fn (): \App\Command\ImportProductsCommand => ($container->privates['App\\Command\\ImportProductsCommand'] ?? $container->load('getImportProductsCommandService')));
    }
}
