framework:
    messenger:
        transports:
            message_out:
                dsn: '%env(KAFKA_DSN)%'
                serializer: 'App\Serializer\ProductMessageSerializer'
                options:
                    flushInterval: 10000
                    flushRetries: 5
                    commitAsync: true
                    auto_commit: false
                    receiveTimeout: 10000
                    topic:
                        name: '%env(KAFKA_TOPIC)%'
                    kafka_conf:
                        security.protocol: 'sasl_ssl'
                        ssl.ca.location: '/usr/local/share/ca-certificates/Yandex/YandexCA.crt'
                        sasl.username: '%env(KAFKA_USERNAME)%'
                        sasl.password: '%env(KAFKA_PASSWORD)%'
                        sasl.mechanisms: 'SCRAM-SHA-512'

            message_in:
                dsn: '%env(KAFKA_DSN)%'
                serializer: 'App\Serializer\ProductMessageSerializer'
                options:
                    flushInterval: 10000
                    flushRetries: 5
                    commitAsync: true
                    auto_commit: false
                    receiveTimeout: 10000
                    topic:
                        name: '%env(KAFKA_TOPIC)%'
                    kafka_conf:
                        security.protocol: 'sasl_ssl'
                        ssl.ca.location: '/usr/local/share/ca-certificates/Yandex/YandexCA.crt'
                        sasl.username: '%env(KAFKA_USERNAME)%'
                        sasl.password: '%env(KAFKA_PASSWORD)%'
                        sasl.mechanisms: 'SCRAM-SHA-512'
                        group.id: '%env(KAFKA_GROUP_ID)%'

        routing:
            App\Message\ProductMessage: message_out
            App\MessageHandler\ProductMessageHandler: message_in

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
