<?php

namespace ContainerLfNfrqY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1BAl6TvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1BAl6Tv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1BAl6Tv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'message_out' => ['privates', 'messenger.transport.message_out', 'getMessenger_Transport_MessageOutService', true],
            'message_in' => ['privates', 'messenger.transport.message_in', 'getMessenger_Transport_MessageInService', true],
            'messenger.transport.message_out' => ['privates', 'messenger.transport.message_out', 'getMessenger_Transport_MessageOutService', true],
            'messenger.transport.message_in' => ['privates', 'messenger.transport.message_in', 'getMessenger_Transport_MessageInService', true],
        ], [
            'message_out' => '?',
            'message_in' => '?',
            'messenger.transport.message_out' => '?',
            'messenger.transport.message_in' => '?',
        ]);
    }
}
