<?php

namespace ContainerLfNfrqY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElasticServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ElasticService' shared autowired service.
     *
     * @return \App\Service\ElasticService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ElasticService.php';

        return $container->privates['App\\Service\\ElasticService'] = new \App\Service\ElasticService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
