<?php

namespace ContainerLfNfrqY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKafkaTransportFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Koco\Kafka\Messenger\KafkaTransportFactory' shared service.
     *
     * @return \Koco\Kafka\Messenger\KafkaTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/koco/messenger-kafka/src/Messenger/KafkaTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/koco/messenger-kafka/src/RdKafka/RdKafkaFactory.php';

        return $container->privates['Koco\\Kafka\\Messenger\\KafkaTransportFactory'] = new \Koco\Kafka\Messenger\KafkaTransportFactory(new \Koco\Kafka\RdKafka\RdKafkaFactory(), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
