<?php

namespace ContainerLfNfrqY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductMessageDispatcherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Message\ProductMessageDispatcher' shared autowired service.
     *
     * @return \App\Message\ProductMessageDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Message/ProductMessageDispatcher.php';

        $container->services['App\\Message\\ProductMessageDispatcher'] = $instance = new \App\Message\ProductMessageDispatcher(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Message\\ProductMessageDispatcher', $container));

        return $instance;
    }
}
