<?php

namespace Container5By0Nsx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestProxyTransportFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Koco\Kafka\Messenger\RestProxyTransportFactory' shared service.
     *
     * @return \Koco\Kafka\Messenger\RestProxyTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/koco/messenger-kafka/src/Messenger/RestProxyTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/Psr18Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';

        $a = new \Http\Discovery\Psr17Factory();

        return $container->privates['Koco\\Kafka\\Messenger\\RestProxyTransportFactory'] = new \Koco\Kafka\Messenger\RestProxyTransportFactory(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), new \Symfony\Component\HttpClient\Psr18Client(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $a, $a), $a, $a, $a);
    }
}
