<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5By0Nsx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5By0Nsx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5By0Nsx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5By0Nsx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5By0Nsx\App_KernelDevDebugContainer([
    'container.build_hash' => '5By0Nsx',
    'container.build_id' => '7c3a4a0c',
    'container.build_time' => 1728906099,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5By0Nsx');
